[package]
name = "lenga-server"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
tonic = "0.11"
tokio = { version = "1", features = ["full"] }
prost = "0.12"
prost-types = "0.12"

[build-dependencies]

tonic-build = "0.11"
